MakinoSCF
CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment pull request #16
Opened 2021-09-30 17:26 UTC by Glinland

2021-10-05 21:32 UTC, Glinland commented
Pull request

2021-10-12 15:17 UTC, shots47s requested changes
SCF code looks good, PEP8 compliance good, the testing code is incorrect, as you redefined the fixture and had some variables outside of the function scope.

2021-10-12 15:17 UTC, shots47s commented on SCF.py
> +from pyscf import gto
Should not need this import here.

2021-10-12 15:17 UTC, shots47s commented on SCF.py
>      """
Extraneous comment block, please remove.

2021-10-12 15:17 UTC, shots47s commented on SCF.py
>      """
Extraneous comment block, please remove.

2021-10-12 15:17 UTC, shots47s commented on SCF.py
> +    for mu in range(num_aos):
Note: could do with two loops and a numpy sum:

```python
Duv[mu, nu] = 2.0*(mo_coeffs_[mu, :nelec]
                               * mo_coeffs_[nu, :nelec]).sum()
```

2021-10-12 15:17 UTC, shots47s commented on tests/SCF/test_SCF.py
> +sys.path.append("/Users/mkx/Desktop/Courses/Python/HF_SCF_Assignment")
Have no idea why this is here.

2021-10-12 15:17 UTC, shots47s commented on tests/SCF/test_SCF.py
> +mol_h2o = gto.M(unit="Bohr",
should not do this, this should use the fixture as was shown in class and through the example function. This is already defined in `conftest.py`

2021-10-12 15:17 UTC, shots47s commented on tests/SCF/test_SCF.py
> +Suv = mol_h2o.intor('int1e_ovlp')  # Overlap Integrals
These should not be defined here, they should be called in the actual test functions as this pollutes the global space.

2021-10-12 15:17 UTC, shots47s commented on tests/SCF/test_SCF.py
> +Fuv = SCF.calc_fock_matrix(mol_h2o, Huv, eri, Duv)
This should not be outside of a function.

2021-10-12 15:17 UTC, shots47s commented on tests/SCF/test_SCF.py
> +mol_e, mol_c = SCF.solve_Roothan_equations(Fuv, Suv)
Really should test the whole array.

2021-10-18 11:27 UTC, closed without merging