Without pyscf
CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment pull request #29
Opened 2021-10-08 16:22 UTC by manishsainani

Updated with tests

2021-10-11 12:50 UTC, shots47s requested changes
One PEP8 standard incorrect.

2021-10-11 12:50 UTC, shots47s commented on SCF.py
> +
failing pycodestyle test on this line because it appears there is whitespace in this line, make sure that all this line contains is a new line.

2021-10-11 13:21 UTC, manishsainani commented
Hello Prof. Brown,
Should I put a \n at the end of the last line or should I just press enter
and save?
It shows error when I put \n at the end.

Regards,
Manish Sainani

On Mon, Oct 11, 2021, 8:50 AM Shawn Brown ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> One PEP8 standard incorrect.
> ------------------------------
>
> In SCF.py
> <https://github.com/CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment/pull/29#discussion_r726088353>
> :
>
> > \ No newline at end of file
> +    return Etot
> +
>
> failing pycodestyle test on this line because it appears there is
> whitespace in this line, make sure that all this line contains is a new
> line.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment/pull/29#pullrequestreview-776195130>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNUGP6HFW3GNDCK6BFN5RDUGLMSTANCNFSM5FT7CZYA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-11 13:31 UTC, shots47s commented
Just a blank line. No space in the line.

On Mon, Oct 11, 2021 at 9:21 AM manishsainani ***@***.***>
wrote:

> Hello Prof. Brown,
> Should I put a \n at the end of the last line or should I just press enter
> and save?
> It shows error when I put \n at the end.
>
> Regards,
> Manish Sainani
>
> On Mon, Oct 11, 2021, 8:50 AM Shawn Brown ***@***.***> wrote:
>
> > ***@***.**** requested changes on this pull request.
> >
> > One PEP8 standard incorrect.
> > ------------------------------
> >
> > In SCF.py
> > <
> https://github.com/CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment/pull/29#discussion_r726088353
> >
> > :
> >
> > > \ No newline at end of file
> > + return Etot
> > +
> >
> > failing pycodestyle test on this line because it appears there is
> > whitespace in this line, make sure that all this line contains is a new
> > line.
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment/pull/29#pullrequestreview-776195130
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AVNUGP6HFW3GNDCK6BFN5RDUGLMSTANCNFSM5FT7CZYA
> >
> > .
> > Triage notifications on the go with GitHub Mobile for iOS
> > <
> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675
> >
> > or Android
> > <
> https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub
> >.
> >
> >
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment/pull/29#issuecomment-940026536>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAACL5534KYHP2X27MRPEM3UGLQETANCNFSM5FT7CZYA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-11 13:34 UTC, shots47s commented
Remember, you can run pycodestyle manually to test if it is working prior
to checking in.

On Mon, Oct 11, 2021 at 9:31 AM Shawn T. Brown ***@***.***>
wrote:

> Just a blank line. No space in the line.
>
> On Mon, Oct 11, 2021 at 9:21 AM manishsainani ***@***.***>
> wrote:
>
>> Hello Prof. Brown,
>> Should I put a \n at the end of the last line or should I just press enter
>> and save?
>> It shows error when I put \n at the end.
>>
>> Regards,
>> Manish Sainani
>>
>> On Mon, Oct 11, 2021, 8:50 AM Shawn Brown ***@***.***> wrote:
>>
>> > ***@***.**** requested changes on this pull request.
>> >
>> > One PEP8 standard incorrect.
>> > ------------------------------
>> >
>> > In SCF.py
>> > <
>> https://github.com/CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment/pull/29#discussion_r726088353
>> >
>> > :
>> >
>> > > \ No newline at end of file
>> > + return Etot
>> > +
>> >
>> > failing pycodestyle test on this line because it appears there is
>> > whitespace in this line, make sure that all this line contains is a new
>> > line.
>> >
>> > —
>> > You are receiving this because you were assigned.
>> > Reply to this email directly, view it on GitHub
>> > <
>> https://github.com/CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment/pull/29#pullrequestreview-776195130
>> >,
>> > or unsubscribe
>> > <
>> https://github.com/notifications/unsubscribe-auth/AVNUGP6HFW3GNDCK6BFN5RDUGLMSTANCNFSM5FT7CZYA
>> >
>> > .
>> > Triage notifications on the go with GitHub Mobile for iOS
>> > <
>> https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675
>> >
>> > or Android
>> > <
>> https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub
>> >.
>> >
>> >
>>
>> —
>> You are receiving this because your review was requested.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/CMU-MS-DAS-Modern-Programming-Mini/HF_SCF_Assignment/pull/29#issuecomment-940026536>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAACL5534KYHP2X27MRPEM3UGLQETANCNFSM5FT7CZYA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-10-12 13:58 UTC, shots47s requested changes
Travis CI failing due to PEP8 compliance and the pytests for SCF are not using the fixture to get the Suv, Tuv, Vuv, and eri matrices. This introduces an external data requirement that is local to that test, defeating the purpose of having the fixture in the first place.

2021-10-12 13:58 UTC, shots47s commented on tests/SCF/test_SCF.py
> +def test_calc_hcore_matrix():  # checks Hcore matrix
This should be using the fixture, it is incorrect to load these in every test, please look at `test_calc_initial_density` where I pass the fixture as I specified in class.

2021-10-12 13:58 UTC, shots47s commented on tests/SCF/test_SCF.py
> +Suv = pickle.load(open("suv.pkl", "rb"))
These are already included in the fixture, with functions that are available to get these matrices, this should be all doen through the fixture as now you have two sets of functionality in here.

2021-10-12 13:58 UTC, shots47s commented on tests/SCF/test_SCF.py
> +    Huv = SCF.calc_hcore_matrix(Tuv, Vuv)
Tuv and Vuv should be accessed through the fixture rather than the global variables above.

2021-10-12 13:58 UTC, shots47s commented on tests/SCF/test_SCF.py
> +def test_solve_Roothan_equations(mol_h2o):  # checks Roothan euations (eigen vectors and eigen values)
Tuv, Vuv should be accessed through the Fixture, not the global variables above.

2021-10-12 13:58 UTC, shots47s commented on tests/SCF/test_SCF.py
> +def test_solve_Roothan_equations(mol_h2o):  # checks Roothan euations (eigen vectors and eigen values)
Suv should be accessed through the fixture and not a global variables.

2021-10-12 13:58 UTC, shots47s commented on tests/SCF/test_SCF.py
> +    Huv = SCF.calc_hcore_matrix(Tuv, Vuv)
Tuv, Vuv, eri should not be accessed through the fixture.

2021-10-12 13:58 UTC, shots47s commented on tests/SCF/test_SCF.py
> +
Tuv, Vuv, eri, Suv should be accessed through the fixture.

2021-10-12 14:01 UTC, shots47s commented
Had to resolve merge conflict to proceed.

2021-10-18 11:28 UTC, closed without merging